dist: trusty
sudo: required
language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "O3337iQ9rOOnc9fBYLAu7yoJftNHBoGqNJ/fh1usZIVGQK2Idrk4BZ4PqjEePtYJaqtBpRFqdPTVgOc/MADncfnXWvi/1G0yGQeLXmpKMT5JdIBC6NmT+A+QpDOOwwYo6TU9qKmmlh8ED5KPYxTfHkxc5IhIu0xafU/tIUj2V10="

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

script:
  # disable integration and performance tests, since we don't have a MarkLogic instance to use
  - ./gradlew check jacocoTestReport -PskipIntegrationTest -PskipPerformanceTest

after_success:
  # codecov.io integration https://codecov.io/gh/marklogic/corb2/branch/development
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
  # codacy https://www.codacy.com/app/mads-hansen/corb2/dashboard
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  # coveralls.io
  - ./gradlew jacocoTestReport coveralls -PskipIntegrationTest -PskipPerformanceTest

addons:
  sonarcloud:
    organization: "default"
    branches:
            - master
            - development

  #srcclr: true

  coverity_scan:
    project:
      name: "marklogic/corb2"
      description: "CoRB is a Java tool designed for bulk content-reprocessing of documents stored in MarkLogic."
    notification_email: mads.hansen@marklogic.com
    build_command_prepend: ""
    build_command:   "./gradle2 build -PskipIntegrationTest -PskipPerformanceTest -S"
    branch_pattern: master
