language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "O3337iQ9rOOnc9fBYLAu7yoJftNHBoGqNJ/fh1usZIVGQK2Idrk4BZ4PqjEePtYJaqtBpRFqdPTVgOc/MADncfnXWvi/1G0yGQeLXmpKMT5JdIBC6NmT+A+QpDOOwwYo6TU9qKmmlh8ED5KPYxTfHkxc5IhIu0xafU/tIUj2V10="

before_install:
  # adding codacy code coverage
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

script:
  # disable integration and performance tests, since we don't have a MarkLogic instance to use
  - ./gradlew check jacocoTestReport -PskipIntegrationTest -PskipPerformanceTest
  # sonarqube.com https://sonarqube.com/dashboard?id=com.marklogic%3Amarklogic-corb%3Adevelopment
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.junit.reportsPath=build/test-results -Dsonar.jacoco.reportPaths=build/jacoco/test.exec -Dsonar.sources=src/main/java

after_success:
  # codecov.io integration https://codecov.io/gh/marklogic/corb2/branch/development
  - bash <(curl -s https://codecov.io/bash)
  # codacy https://www.codacy.com/app/mads-hansen/corb2/dashboard
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  # coveralls.io
  - ./gradlew jacocoTestReport coveralls -PskipIntegrationTest -PskipPerformanceTest
  
addons:
  sonarqube:
      branches: 
        - master
        - development

  coverity_scan:
    project:
      name: "marklogic/corb2"
      description: "CoRB is a Java tool designed for bulk content-reprocessing of documents stored in MarkLogic."
    notification_email: mads.hansen@marklogic.com
    build_command_prepend: ""
    build_command:   "./gradle2 build -PskipIntegrationTest -PskipPerformanceTest -S"
    branch_pattern: master
